apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: tf-notebook-
  labels:
    app: tf-notebook
spec:
  selector:
    matchLabels:
      app: tf-notebook
  template:
    metadata:
      labels:
        app: tf-notebook
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      securityContext:
        fsGroup: 0
      containers:
        - name: tf-notebook
          image: tensorflow/tensorflow:2.15.0-gpu-jupyter
          resources:
            limits:
              cpu: 4000m
              memory: 5120M
              ephemeral-storage: 10G
              nvidia.com/gpu: 1
            requests:
              cpu: 4000m
              memory: 5120M
              ephemeral-storage: 10G
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8888
          env:
            - name: JUPYTER_TOKEN
              value: ""
              required: true
            - name: TEST
              value: ""
          volumeMounts:
            - mountPath: /mnt/data
