apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-cosmos
spec:
  selector:
    matchLabels:
      name: DEPLOYMENT_INFORMATION
  template:
    metadata:
      labels:
        name: DEPLOYMENT_INFORMATION
    spec:
      dnsPolicy: "None"  # Required when overriding dnsConfig
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      nodeSelector:
        kubernetes.io/hostname: NODE_SELECTOR  # Placeholder that will get replaced
      containers:
        - name: cosmos-nim
          image: nvcr.io/nim/nvidia/cosmos-predict1-7b-text2world:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: NGC_API_KEY
              value: "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"
          volumeMounts:
            - name: nim-cache
              mountPath: /opt/nim/.cache
            - name: "VOLUME_NAME"         # must use "" in the volumes section, not here
              mountPath: MOUNT_PATH       # must NOT use "" here, or it will not deploy
          resources:
            limits:
              nvidia.com/gpu: GPU_LIMIT                # Placeholder for GPU limit
              cpu: CPU_LIMIT                           # Placeholder for CPU limit
              memory: MEMORY_LIMIT                     # Placeholder for memory limit (e.g., "4Gi")
              ephemeral-storage: STORAGE_LIMIT         # Placeholder for storage limit (e.g., "10Gi")
            requests:
              nvidia.com/gpu: GPU_REQUEST              # Placeholder for GPU request
              cpu: CPU_REQUEST                         # Placeholder for CPU request
              memory: MEMORY_REQUEST                   # Placeholder for memory request (e.g., "2Gi")
              ephemeral-storage: STORAGE_REQUEST       # Placeholder for storage request (e.g., "5Gi")
      volumes:
        - name: nim-cache
          emptyDir: {}
        - name: "VOLUME_NAME"  # must use "" here, or it will not deploy
          hostPath:
            path: HOST_PATH    # must NOT use "" here, or it will not deploy
            type: DirectoryOrCreate
      imagePullSecrets:
        - name: sercret-nvidia
      restartPolicy: Always
