apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-cosmos
spec:
  selector:
    matchLabels:
      name: DEPLOYMENT_INFORMATION
  template:
    metadata:
      labels:
        name: DEPLOYMENT_INFORMATION
    spec:
      nodeSelector:
        kubernetes.io/hostname: NODE_SELECTOR # This is a placeholder that will get replaced
      containers:
      - name: cosmos-nim
        image: nvcr.io/nim/nvidia/cosmos-predict1-7b-text2world:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: nim-cache
          mountPath: /opt/nim/.cache
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
      volumes:
      - name: nim-cache
        emptyDir: {}
      imagePullSecrets:
      - name: sercret-nvidia
      restartPolicy: Always
