apiVersion: v1
kind: Service
metadata:
  name: nim-cosmos-service
spec:
  selector:
    deploymentInformation: DEPLOYMENT_INFORMATION # This is a placeholder that will get replaced
  ports:
    - name: tcp
      port: 80  # Port exposed by the service
      protocol: TCP
      targetPort: 8000  # Port on the pod
  type: ClusterIP
