apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-notebook
spec:
  selector:
    matchLabels:
      flux-deployment-id: tf-notebook
  template:
    metadata:
      labels:
        flux-deployment-id: tf-notebook
    spec:
      containers: []  # No containers defined here, to be handled in patches
