apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-notebook
spec:
  selector:
    matchLabels:
      app: tf-notebook
  template:
    metadata:
      labels:
        app: tf-notebook
    spec:
      containers:
      - name: placeholder
        image: busybox
        command: ["sleep", "infinity"]
