apiVersion: v1
kind: Service
metadata:
  name: -tf-notebook-service-argocd
spec:
  selector:
    flux-deployment-id: DEPLOYMENT_INFORMATION # Placeholder to be replaced
  ports: []  # No ports defined here
