apiVersion: v1
kind: Service
metadata:
  name: tf-notebook-service
spec:
  selector:
    deploymentInformation: value-service
  ports:
    - name: tcp
      port: 80  # Port exposed by the service
      protocol: TCP
      targetPort: 8000  # Port on the pod
  type: ClusterIP
