apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-cosmos
spec:
  selector:
    matchLabels:
      name: DEPLOYMENT_INFORMATION
  template:
    metadata:
      labels:
        name: DEPLOYMENT_INFORMATION
    spec:
      nodeSelector:
        kubernetes.io/hostname: NODE_SELECTOR  # Placeholder that will get replaced
      containers:
        - name: cosmos-nim
          image: nvcr.io/nim/nvidia/cosmos-predict1-7b-text2world:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nim-cache
              mountPath: /opt/nim/.cache
            - name: '16081'
              mountPath: /mnt/data
          resources:
            limits:
              nvidia.com/gpu: GPU_LIMIT  # Placeholder for GPU limit
              cpu: CPU_LIMIT             # Placeholder for CPU limit
              memory: MEMORY_LIMIT       # Placeholder for memory limit (e.g., "4Gi")
              ephemeral-storage: STORAGE_LIMIT  # Placeholder for storage limit (e.g., "10Gi")
            requests:
              nvidia.com/gpu: GPU_REQUEST  # Placeholder for GPU request
              cpu: CPU_REQUEST             # Placeholder for CPU request
              memory: MEMORY_REQUEST       # Placeholder for memory request (e.g., "2Gi")
              ephemeral-storage: STORAGE_REQUEST  # Placeholder for storage request (e.g., "5Gi")
      volumes:
        - name: nim-cache
          emptyDir: {}
        - name: '16081'
          hostPath:
            path: /tmp/fluxedge/16081
            type: DirectoryOrCreate
      imagePullSecrets:
        - name: secret-nvidia
      restartPolicy: Always
