apiVersion: v1
kind: Service
metadata:
  name: -tf-notebook-service-argocd
spec:
  selector:
    flux-deployment-id: DEPLOYMENT_INFORMATION # This is a placeholder that will get replaced
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
