apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ollama  # Adjust this path as needed
namePrefix: DEPLOYMENT_INFORMATION  # Prefix for resource names
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
  - path: service-patch.yaml
    target:
      kind: Service
