apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-cosmos
spec:
  selector:
    matchLabels:
      app: nim-cosmos
  template:
    metadata:
      labels:
        app: nim-cosmos
    spec:
      containers: []  # No containers defined here, to be handled in patches
